### ISSUE TITLE
UE5 里HitResult.Actor应该改成哪个属性？

### ISSUE THREAD

**Issue by mkygogo** [chexiongsheng/BlockBreakerStarter#1]
![TWKXNZDESMM8)FIRICY{G1P](https://github.com/chexiongsheng/BlockBreakerStarter/assets/34338922/fb0ad7cf-b72c-4bf5-9209-7431d34dff48)

**Comment by chexiongsheng** [comment]
看UE文档
或者看看HitResult的定义。

**Comment by mkygogo** [comment]
改成hitResult.HitObjectHandle.Actor, 编辑器里不报错了，但是好像运行还是不对，射击绿色墙壁的时候还是没反应
